[package]
name = "RPG"
version = "0.1.0"
authors = ["Idang1410 <Idang1410@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
